HyperloopUPV-H8/software

backend/pkg/transport/packet/data.go, backend/pkg/transport/packet/value.go, backend/pkg/transport/presentation/decoder.go, backend/pkg/transport/presentation/decoder/data.go, backend/pkg/transport/presentation/decoder/decoder.go, backend/pkg/transport/presentation/errors.go, backend/pkg/transport/transport.go
The `decoder` takes all incoming communications and turns the raw binary into concrete go structs.
This first PR covers the root decoder, `Packet` and the data decoder `data`. 
The root decoder reads the id of the packet and chooses the appropriate decoder to keep decoding the message.
The data decoder decodes packets based on the structure defined on the ADE.
=> [backend] [pr1] packet decoder

backend/pkg/transport/packet/protection/decoder.go, backend/pkg/transport/packet/protection/errors.go, backend/pkg/transport/packet/protection/kind.go, backend/pkg/transport/packet/protection/packet.go
The protection messages are currently encoded as JSON, although they will later on have their own encoding similar to other packets to reduce load and bandwidth usage.
This PR implements the protection message decoding. It defines the protection model and provides functions to decode the json stream.
=> [backend] [pr2] protection decoder

backend/pkg/transport/packet/data/codec.go, backend/pkg/transport/packet/data/descriptors.go, backend/pkg/transport/packet/data/encoder.go, backend/pkg/transport/packet/data/errors.go, backend/pkg/transport/presentation/encoder.go, backend/pkg/transport/presentation/encoder_test.go, backend/pkg/transport/transport.go
This PR adds the encoder for packets. The encoder is used to serialize the orders we want to send to the vehicle. Orders are like data packets and use the same structs to define the order.
I've also added tests to check the functionality works correctly
=> [backend] packet encoder

backend/pkg/abstraction/transport.go, backend/pkg/transport/constructor.go, backend/pkg/transport/errors.go, backend/pkg/transport/messages.go, backend/pkg/transport/network/tcp/client.go, backend/pkg/transport/network/tcp/conn.go, backend/pkg/transport/network/tcp/server.go, backend/pkg/transport/notifications.go, backend/pkg/transport/session/sniffer.go, backend/pkg/transport/transport.go
This is the first of two PRs that implement the transport functionality on the already existing code. On this one I implemented the internal implementation of the transport module, which takes the `sniffer`, `tcp`, `decoder`, `encoder`, `tftp`, etc. And puts it all together in a (hopefully) nice to use interface.
The current way to build and use the transport module is very manual in nature, having to specify everything yourself and having to construct the independent parts beforehand. The idea is to improve this way of building it over time, but for now this should work fine.
=> [backend] [PR1] transport implementation

backend/cmd/main.go, backend/pkg/transport/packet/data/converter.go, backend/pkg/transport/packet/data/descriptors.go, backend/pkg/transport/presentation/decoder_test.go, backend/pkg/transport/presentation/encoder_test.go
This PR implements the unit converter in the new transport logic. The new converter is embedded into the description of the measurements, applying conversions when decoding.
All the other code has been updated to take this into consideration
=> [backend] Unit Converter

backend/pkg/transport/network/tcp/client.go, backend/pkg/transport/transport.go
The previous implementation had a bug where after connection to a board acting as server was lost the system will abort trying to connect due to how errors were handled, the new implementation should fix this
=> [backend] TCP connections not reconnecting after link goes down

backend/cmd/main.go, backend/internal/update_factory/update_factory.go, backend/pkg/broker/topics/connection/update.go, backend/pkg/vehicle/vehicle.go, common-front/lib/adapters/ConnectionUpdate.ts, common-front/lib/components/Connections/useConnections.ts, common-front/lib/store/connectionsStore.ts, common-front/lib/store/measurementsStore.ts, common-front/lib/store/podDataStore.ts
Under request from firmware, the values of packets reset when a board reconnects.
The backend now just resets the values on the update factory and on the frontend the stores get updated when receiving a notification from the backend.
To make the change work, the logic of the update topic had to be changed because before all connection statuses would be sent when a connection got updated and now instead just the updated connection gets broadcasted. This logic made it a pain to detect changes on the frontend, so this new logic simplifies that.
=> [ethernet-view] reset packet information when board reconnects

ethernet-view/src/components/OrdersContainer/Orders/BoardOrders/BoardOrders.module.scss, ethernet-view/src/components/OrdersContainer/Orders/BoardOrders/BoardOrders.tsx
A tiny feature that allows to collapse the orders section by boards, as the packets section does.
=> [ethernet-view] Collapsable orders

backend/pkg/logger/data/logger.go
This hotfix solves a variable shadowing in the data sublogger that prevented new files from being created. The file-existence check was obscured by a previous check, making the check's output always 'true', meaning the file was expected to exist when it didn't.
=> [backend] Logger Hotfix

backend/pkg/logger/data/logger.go, backend/pkg/logger/logger.go, backend/pkg/logger/protection/logger.go
There were two bugs in the logger:
* The log timestamp was just set the first time the app runs, meaning consecutive logs without reloading overwrite the previous one, now the timestamp gets calculated every time the start mehtod is invoked
* The data and proteciton subloggers didn't clear the file map, this meant that the logs were being written to an already closed file because upon reading the map, an entry already existed, but that entry was closed.
=> Fix logger file naming and close procedures

.gitignore, backend/cmd/main.go, backend/pkg/broker/topics/logger/enable.go, backend/pkg/broker/topics/order/send.go, backend/pkg/broker/topics/order/state.go, backend/pkg/vehicle/vehicle.go, common-front/lib/components/Orders/useOrders.ts, common-front/lib/store/ordersStore.ts, ethernet-view/src/components/OrdersContainer/Orders/Orders.tsx, go.work, state-order-tester/.gitignore, state-order-tester/go.mod, state-order-tester/main.go
Added the half-implemented state order feature. State orders are orders that are enabled depending on the board state. When the board changes state it sends a diff of the state orders and those get updated on the fronted. When a board disconnects, the state orders are resetted for that board
=> [ethernet-view] Working State Orders

backend/pkg/logger/data/logger.go, backend/pkg/logger/order/logger.go, backend/pkg/logger/protection/logger.go, backend/pkg/logger/state/logger.go, backend/pkg/vehicle/notification.go
- Invert folder order on the logs so it's timestamp/data and timestamp/order instead of data/timestamp and order/timestamp.
- Show board names instead of ip address on data logs.
=> [Backend] Logger QOL updates

backend/internal/adj/git.go, backend/pkg/adj/git.go
Cloning the ADJ to a temp file will check for accessibility to the repo as well as internet connection. If the repo is unreachable, the backend will work with the local ADJ.
=> [Backend] Clone a temp ADJ to check internet connection

backend/pkg/transport/network/tcp/client.go
Avoid overflowing the console when dialing fails by correctly implementing the exponential backoff function in the code.
=> [Backend] Avoid overflooding console with exponential backoff

backend/cmd/config.go, backend/cmd/config.toml, backend/cmd/main.go, backend/pkg/transport/transport.go
When the backend receives a packet with id = 0, it will send it to all other boards, only when enabled on the config.toml.
=> [Backend] Propagate fault

backend/internal/adj/git.go, backend/pkg/adj/git.go
Small QOL change: Warn the user when the remote ADJ could not be cloned and the local ADJ is being used. Before this, there was no way of knowing if the remote ADJ cloning was successful or not.
=> [Backend] Warn when using local ADJ

.github/workflows/test-dev-scripts.yaml, scripts/README.md, scripts/dev-unified.sh, scripts/dev.cmd, scripts/dev.ps1, scripts/dev.sh
=> Dev shell for windows

backend/cmd/main.go, backend/pkg/boards/blcu.go, backend/pkg/boards/blcu_integration_test.go, backend/pkg/boards/blcu_simple_test.go, backend/pkg/broker/topics/blcu/blcu_test.go, backend/pkg/broker/topics/blcu/download.go, backend/pkg/broker/topics/blcu/upload.go, backend/pkg/vehicle/vehicle.go
Also adds tests for the BLCU topics and functions.
closes #250
=> BLCU improvements

backend/cmd/config.go, backend/cmd/config.toml, backend/cmd/main.go, backend/go.mod, backend/pkg/transport/network/tcp/client.go, backend/pkg/transport/network/tcp/reconnection_test.go, backend/pkg/transport/network/tcp/simple_reconnection_test.go, backend/pkg/transport/transport.go, backend/pkg/transport/transport_test.go, go.work.sum
- Fixed TCP retries making boards unabler to reconnect
- TCP protocol setting accessible through `config.toml`
- New Transport (TCP) tests
- Improvement of `config.toml`
Closes #313
=> TCP settings

ethernet-view/src/components/ChartMenu/ChartElement/ChartElement.tsx, ethernet-view/src/components/ChartMenu/ChartMenu.tsx, ethernet-view/src/pages/TestingPage/ChartsColumn/ChartsColumn.tsx, ethernet-view/src/pages/TestingPage/TestingPage.tsx
Also, changed the 'Show'/'Hide' buttons to english.
Closes #334
=> [Ethernet view] Save plotted variables on a higher level so they aren't destroyed when closing the plots window
